### ISSUE TITLE
How can I install this program?

### ISSUE THREAD

**Issue by d9394** [madflow/qnap-radicale#1]
I can't find this program in the app center of qnap, so how can I install into a qnap system 4.2.0?

**Comment by madflow** [comment]
Hi!

First a word a of caution: 

1 This works for me (QNAP 219) - It might not work on your system.
2 The Web Config Interface is not secured.
3 As far as by now: You will have to edit the "Auth" and "Rights" file by hand.

You can find a prebuild package here:

https://github.com/madflow/qnap-radicale/releases

This is the release that runs on my NAS and works perfectly for me. It is not in the app repository because I am not satisfied how QNAP fosters (or does not) Open Source App development.

After installation you can find the web interface here:

http://{YOURNAS_IP}:5000

Let me know if you are stuck somewhere.

Radicale Docs:
- http://radicale.org/user_documentation/ 

I use Davdroid and "Vanilla" Caldav from iOS9 as clients.
